customer/urls.py
from django.urls import path
from .views import *


app_name = 'customer'

urlpatterns = [
    path('', CustomerList.as_view(), name='customer-list'),
    path('create/', CustomerCreate.as_view(), name='customer-create'),
    path('update/<int:id>/', CustomerUpdate.as_view(), name='customer-update'),
    path('<int:pk>/', CustomerDetail.as_view(),name='customer-detail'),
    path('delete/<int:pk>/', CustomerDelete.as_view(), name='customer-delete'),

	]

vx/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from product.views import (
                    ProductDetailView,
                    )
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home-page'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('product/', include('product.urls')),
    path('purchase/', include('purchase.urls')),
    path('sell/', include('sell.urls')),
    path('product/<int:id>/', ProductDetailView.as_view(),name='product-detail'),
    path('customer/', include('customer.urls')),

]

customer/models.py
from django.db import models
from django.urls import reverse

class Customer(models.Model):
    name = models.CharField(max_length=20)
    STATUS = (
        ('C', 'Converter'),
        ('E', 'Enduser'),
        ('D', 'Distributor'),
        ('A', 'Agent')
        )
    status = models.CharField(max_length=1,choices=STATUS,default='C')
    country = models.CharField(max_length=2,default='HR')
    CATEGORY = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4)
        )
    category = models.PositiveSmallIntegerField(choices=CATEGORY,default=2)
    issue = models.CharField(max_length=50, blank=True)


    class Meta:
        db_table = 'customer'
        ordering = ('country','name','status','category','issue')

    def __str__(self):
        return self.name

customer/forms.py
from django import forms

from .models import Customer


class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = []

customer/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
                            CreateView,
                            DeleteView,
                            DetailView,
                            ListView,
                            UpdateView
)
from .forms import CustomerModelForm
from .models import Customer
from sell.models import *

class CustomerList(LoginRequiredMixin, ListView):
    model = Customer

class CustomerDetail(LoginRequiredMixin, DetailView):
    model = Customer

    def get_context_data(self, **kwargs):
        context = super(CustomerDetail, self).get_context_data(**kwargs)
        customer = kwargs.get('object', None)
        converter_sales = customer.converter_sales.all()
        prods = SellItem.objects.filter(sell_id__in=converter_sales)
        proj_product_list = customer.front_partner_projects.all()
        if prods or proj_product_list:
            context.update({'prods': prods, 'proj_product_list': proj_product_list})
        return context


class CustomerCreate(LoginRequiredMixin, CreateView):
    template_name = 'customer/customer_create.html'
    form_class = CustomerModelForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('customer:customer-list')

class CustomerUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'customer/customer_create.html'
    form_class = CustomerModelForm

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Customer, id=id_)

    def get_success_url(self):
        return reverse('customer:customer-list')


class CustomerDelete(LoginRequiredMixin, DeleteView):
    model = Customer
    template_name = 'customer/customer_delete.html'
    success_url = reverse_lazy('customer:customer-list')

customer/templates/customer/customer_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h2>Enter new customer:</h2>

<form action='.' method="post">{% csrf_token %}
    {{ form | crispy}}
    <input type="submit" value="Save">
</form>
<br>
<a class="btn btn-outline-info btn-sm" href="{% url 'customer:customer-list' %}">Back to Customer List</a>


{% endblock %}

customer/templates/customer/customer_delete.html
{% extends "purchase/purchase_detail.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong> {{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

customer/templates/customer/customer_detail.html
{% extends "base.html" %}
{% load table_operations %}
{% block head_title %}{{object.l_name}}{% endblock %}
{% block content %}

<h4>Customer details</h4>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group mr-2" role="group" aria-label="First group">
  <a class="btn btn-outline-warning btn-sm" href="{% url 'customer:customer-update' object.id %}">Update</a>
  <a class="btn btn-outline-danger btn-sm" href="{% url 'customer:customer-delete' object.id %}">Delete</a>
  <a class="btn btn-outline-info btn-sm" href="{% url 'customer:customer-list' %}">Back to Customer List</a>
</div>
</div>
<table class="table table-sm">
   <thead>
     <tr>
       <th style="width: 10%" class="table-primary">C-ry</th>
       <th style="width: 20%" class="table-success">Name</th>
       <th style="width: 10%" class="table-dark">Stat</th>
       <th style="width: 10%" class="table-danger">Cat</th>
       <th class="table-warning">issue</th>
     </tr>
   </thead>
   <tbody>
     <tr>
       <td class="table-primary">{{ object.country }} </td>
       <td class="table-success">{{object.name}}</td>
       <td class="table-dark">{{object.get_status_display }}</td>
       <td class="table-danger">{{object.category}}</td>
       <td class="table-warning">{{object.issue}}</td>
     </tr>
   </tbody>
 </table>



 <h4>{{object.name}}'s business history:</h4>
 <table id="mydatatable" class="display" style="width:100%">
   <thead>
     <tr>
       <th scope="col">Film</th>
       <th scope="col">Enduser</th>
       <th scope="col">T pa</th>
       <th scope="col">Price</th>
       <th scope="col">EUR</th>
       <th scope="col"></th>
     </tr>
   </thead>
   <tbody>
 {% for i in prods %}
     <tr>
       <td>{{ i.product.name }}</td>
       <td>{{ i.enduser.name }}</td>
       <td>{{ i.quantity }}</td>
       <td>{{ i.price }}</td>
       <td>{{ i.price|mult:i.quantity }}</td>
         {% if i.discontinued == True %}
         <td> discontinued!</td>
         {% else %}
         <td></td>
         {% endif %}
     </tr>
 {% endfor %}
 </tbody>
      <tfoot>
          <tr>
            <th scope="col">Film</th>
            <th scope="col">Enduser</th>
            <th scope="col">T pa</th>
            <th scope="col">Price</th>
            <th scope="col">EUR</th>
            <th scope="col"></th>
          </tr>
      </tfoot>
  </table>
  <h4>{{object.name}} Projects:</h4>
  <table id="mydatatable" class="display" style="width:100%">
    <thead>
      <tr>
        <th scope="col">Film</th>
        <th scope="col">T pa</th>
        <th scope="col">Price</th>
        <th scope="col">Back-par</th>
        <th scope="col">Application</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
  {% for i in proj_product_list %}
      <tr>
        <td>{{ i.product.name }}</td>
        <td>{{ i.quantity }}</td>
        <td>{{ i.price }}</td>
        <td>{{ i.back_partner.name }}</td>
        <td>{{ i.application }}</td>
        {% if i.discontinued == True %}
          <td> discontinued!</td>
          {% else %}
          <td></td>
          {% endif %}
      </tr>
  {% endfor %}
  </tbody>
   </table>


{% endblock %}

customer/templates/customer/customer_list.html
{% extends "base.html" %}
{% block content %}

<h4>Customers:</h4>
  <table id="mydatatable" class="table table-striped table-bordered mydatatable" style="width:100%">
    <thead>
      <tr>
        <th style="width: 10%">C-ry</th>
        <th scope="col">Name</th>
        <th style="width: 10%">Stat</th>
        <th style="width: 10%">Cat</th>
        <th scope="col">Issue</th>
      </tr>
    </thead>
    <tbody>
{% for cust in object_list %}
      <tr>
        <td>{{ cust.country }}</td>
        <td><a href="{% url 'customer:customer-detail' cust.id %}">{{ cust.name }}</td>
        <td>{{ cust.status }}</td>
        <td>{{ cust.category }}</td>
        <td>{{ cust.issue }}</td>
      </tr>
{% endfor %}
    </tbody>
   </table>

<a class="btn btn-outline-primary btn-sm" href="{% url 'customer:customer-create' %}">Create</a>

{% endblock %}