customer/urls.py
from django.urls import path
from .views import *


app_name = 'customer'

urlpatterns = [
    path('', CustomerList.as_view(), name='customer-list'),
    path('create/', CustomerCreate.as_view(), name='customer-create'),
    path('update/<int:id>/', CustomerUpdate.as_view(), name='customer-update'),
    path('<int:pk>/', CustomerDetail.as_view(),name='customer-detail'),
    path('delete/<int:pk>/', CustomerDelete.as_view(), name='customer-delete'),

	]

product/urls.py
from django.urls import path

from .views import (
                    ProductListView,
                    ProductDeleteView,
                    ProductDetailView,
                    ProductCreateView,
                    ProductUpdateView,
                )
app_name = 'product'
urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('<int:id>', ProductDetailView.as_view(),name='product-detail'),
    path('create/', ProductCreateView.as_view(),name='product-create'),
    path('<int:id>/update/', ProductUpdateView.as_view(),name='product-update'),
    path('<int:id>/delete/', ProductDeleteView.as_view(),name='product-delete'),
]

sell/urls.py
from django.urls import path
from .views import *


app_name = 'sell'

urlpatterns = [
    path('', SellList.as_view(), name='sell-list'),
    path('active/', SellItemList.as_view(), name='active-list'),
    path('create/', SellCreate.as_view(), name='sell-create'),
    path('update/<int:pk>/', SellUpdate.as_view(), name='sell-update'),
    path('<int:pk>/', SellDetail.as_view(),name='sell-detail'),
    path('delete/<int:pk>/', SellDelete.as_view(), name='sell-delete'),

	]

vx/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from product.views import (
                    ProductDetailView,
                    )
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home-page'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('product/', include('product.urls')),
    path('purchase/', include('purchase.urls')),
    path('sell/', include('sell.urls')),
    path('product/<int:id>/', ProductDetailView.as_view(),name='product-detail'),
    path('customer/', include('customer.urls')),

]

sell/models.py
from django.db import models
from product.models import Product
from customer.models import Customer
from django.db.models import Q

class Sell(models.Model):
    converter = models.ForeignKey(Customer, null=True, related_name="converter_sales",on_delete=models.SET_NULL, limit_choices_to=Q(status='C') | Q(status='D'))
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'sell'
        ordering = ('converter','-updated_at')
        verbose_name_plural = 'sales'
    def __str__(self):
        return str(self.converter)

class SellItem(models.Model):
    sell = models.ForeignKey(Sell, related_name="has_items",on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=True, related_name="product_sells",on_delete=models.SET_NULL)
    quantity = models.PositiveIntegerField(blank=True)
    price = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    enduser = models.ForeignKey(Customer, blank=True, null=True, related_name="enduser_sales",on_delete=models.SET_NULL, limit_choices_to={'status': 'E'},)
    description = models.CharField(max_length=50, blank=True)
    discontinued = models.BooleanField(default=False)

    class Meta:
        db_table = 'sellitem'
        ordering = ('-quantity',)
        verbose_name_plural = "SellItems"

    def __str__(self):
        return str(self.product)+ '  ' + ' discontinued ' + str(self.discontinued)

sell/forms.py
from django import forms
from .models import *
from django.forms.models import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from .custom_layout_object import *

class SellForm(forms.ModelForm):

    class Meta:
        model = Sell
        exclude = ('created_at','updated_at',)

    def __init__(self, *args, **kwargs):
        super(SellForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Field('converter'),
                Fieldset('Add items',
                    Formset('items')),
                Field('note'),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'save')),
                )
            )


class SellItemForm(forms.ModelForm):

    class Meta:
        model = SellItem
        exclude = ()

SellItemFormSet = inlineformset_factory(
    Sell, SellItem, form=SellItemForm,
    fields=['sell', 'product', 'quantity', 'price', 'enduser', 'description','discontinued'], extra=4
    )

sell/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.db import transaction

class SellList(LoginRequiredMixin, ListView):
    model = Sell

class SellDetail(LoginRequiredMixin, DetailView):
    model = Sell

    def get_context_data(self, **kwargs):
        context = super(SellDetail, self).get_context_data(**kwargs)
        sell_item = kwargs.get('object', None)
        sell_object_list = sell_item.has_items.all()

        if sell_object_list:
            context.update({'sell_object_list': sell_object_list})
        return context

class SellItemList(LoginRequiredMixin, ListView):
    model = SellItem
    template_name = 'sell/sell_active.html'

    def get_context_data(self, **kwargs):
        context = super(SellItemList, self).get_context_data(**kwargs)
        active_list = SellItem.objects.filter(discontinued=False)
        context['active_list'] = active_list
        return context

class SellCreate(LoginRequiredMixin, CreateView):
    model = Sell
    template_name = 'sell/sell_create.html'
    form_class = SellForm
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(SellCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['items'] = SellItemFormSet(self.request.POST)
        else:
            data['items'] = SellItemFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        items = context['items']
        with transaction.atomic():
            self.object = form.save()

            if items.is_valid():
                items.instance = self.object
                items.save()
        return super(SellCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('sell:sell-detail', kwargs={'pk': self.object.pk})

class SellUpdate(LoginRequiredMixin, UpdateView):
    model = Sell
    template_name = 'sell/sell_create.html'
    form_class = SellForm
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(SellUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['items'] = SellItemFormSet(self.request.POST, instance=self.object)
        else:
            data['items'] = SellItemFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        items = context['items']
        with transaction.atomic():
            self.object = form.save()

            if items.is_valid():
                items.instance = self.object
                items.save()
        return super(SellUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('sell:sell-detail', kwargs={'pk': self.object.pk})


class SellDelete(LoginRequiredMixin, DeleteView):
    model = Sell
    template_name = 'sell/sell_delete.html'
    success_url = reverse_lazy('sell:sell-list')

sell/templates/sell/formset.html
{% load crispy_forms_tags %}
{% load static %}
<table class="col-md-9" style="margin-left: 10px;">
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
            <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
                {% endfor %}
            </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</script>
<script src="{% static 'sell/libraries/django-dynamic-formset/jquery.formset.js' %}">
</script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

sell/templates/sell/sell_active.html
{% extends "base.html" %}
{% load table_operations %}
{% block head_title %}{{object.name}}{% endblock %}
{% block content %}

<h2>Active business</h2>
<a class="btn btn-outline-info btn-sm" href="{% url 'sell:sell-create' %}">Create new</a>

    <table id="mydatatable" class="display" style="width:100%">
      <thead>
        <tr>
          <th scope="col">Converter</th>
          <th scope="col">Film</th>
          <th scope="col">T pa</th>
          <th scope="col">Price</th>
          <th scope="col">EUR</th>
         <th scope="col">E.U.</th>
          <th scope="col">Discription</th>
        </tr>
      </thead>
      <tbody>
  {% for i in active_list %}
        <tr>
          <td><a href="{% url 'customer:customer-detail' i.sell.converter.id %}">{{ i.sell.converter }} </td>
          <td><a href="{% url 'product:product-detail' i.product.id %}/">{{ i.product.name }}</td>
          <td> {{ i.quantity }} </td>
          <td> {{ i.price }} </td>
          <td> {{ i.price|mult:i.quantity }} </td>
          <td> {{ i.enduser }} </td>
          <td> {{ i.description }} </td>
        </tr>
  {% endfor %}
  </tbody>
         <tfoot>
             <tr>
               <th scope="col">Converter</th>
               <th scope="col">Film</th>
               <th scope="col">T pa</th>
               <th scope="col">Price</th>
               <th scope="col">EUR</th>
               <th scope="col">E.U.</th>
               <th scope="col">Discription</th>
              </tr>
         </tfoot>
     </table>

</div>

{% endblock %}

sell/templates/sell/sell_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            Create Sales
        </div>
        <div class="card-body">
             {% crispy form %}
        </div>
    </div>
</div>
<br>
<a class="btn btn-outline-info btn-sm" href="{% url 'sell:sell-list' %}">Back to Sales List</a>

{% endblock content %}

sell/templates/sell/sell_delete.html
{% extends "sell/sell_detail.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong> Sales {{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

sell/templates/sell/sell_detail.html
{% extends "base.html" %}
{% load table_operations %}
{% block head_title %}{{object.name}}{% endblock %}
{% block content %}

<h2>{{ object.customer }} business</h2>
<table class="table table-sm">
   <thead>
     <tr>
       <th class="table-primary">Converter</th>
       <th class="table-success">Purchased on</th>
       <th class="table-secondary">Updated</th>
     </tr>
   </thead>
   <tbody>
     <tr>
       <td class="table-primary">{{ object.converter }} </td>
       <td class="table-success">{{object.created_at}}</td>
       <td class="table-secondary">{{object.updated_at}}</td>
     </tr>
   </tbody>
 </table>
    <table id="mydatatable" class="display" style="width:100%">
      <thead>
        <tr>
          <th scope="col">Film</th>
          <th scope="col">E.U.</th>
          <th scope="col">q-ty</th>
          <th scope="col">Price</th>
          <th scope="col">EUR</th>
          <th scope="col">Description</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
  {% for i in sell_object_list %}
        <tr>
          <td><a href="{% url 'product:product-detail' i.product.id %}/">{{ i.product.name }}</td>
          <td> {{ i.enduser }} </td>
          <td> {{ i.quantity }} </td>
          <td> {{ i.price}} </td>
          <td> {{ i.price|mult:i.quantity}} </td>
          <td> {{ i.description }} </td>
          <td>   {% if i.discontinued == True %}
            stopped {% endif %}</td>

        </tr>
  {% endfor %}
  </tbody>
         <tfoot>
             <tr>
               <th scope="col">Film</th>
               <th scope="col">E.U.</th>
               <th scope="col">q-ty</th>
               <th scope="col">Price</th>
               <th scope="col">EUR</th>
               <th scope="col">Description</th>
               <th scope="col"></th>
              </tr>
         </tfoot>
     </table>

<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group mr-2" role="group" aria-label="First group">
  <a class="btn btn-outline-warning btn-sm" href="{% url 'sell:sell-update' object.id %}">Update</a>
  <a class="btn btn-outline-danger btn-sm" href="{% url 'sell:sell-delete' object.id %}">Delete</a>
  <a class="btn btn-outline-info btn-sm" href="{% url 'sell:sell-list' %}">To per converter list</a>
  <a class="btn btn-outline-info btn-sm" href="{% url 'sell:active-list' %}">To active list</a>
</div>
</div>

{% endblock %}

sell/templates/sell/sell_list.html
{% extends "base.html" %}
{% load table_operations %}
{% block content %}

<h4>Sales</h4>
<a class="btn btn-outline-info btn-sm" href="{% url 'sell:sell-create' %}">Create new</a>

  <table id="mydatatable" class="display" style="width:100%">
    <thead>
      <tr>
        <th scope="col">Converter</th>
        <th scope="col">Created Y-M-D</th>
        <th scope="col">Modified Y-M-D</th>
      </tr>
    </thead>
    <tbody>
{% for sale in object_list %}
      <tr>
        <td><a href="{% url 'sell:sell-detail' sale.id %}">{{ sale.converter }}</td>
        <td>{{ sale.created_at|date:'y-m-d' }}</td>
        <td>{{ sale.updated_at|date:'y-m-d'  }}</td>
      </tr>
{% endfor %}
</tbody>

   </table>

{% endblock %}