product/urls.py
from django.urls import path

from .views import (
                    ProductListView,
                    ProductDeleteView,
                    ProductDetailView,
                    ProductCreateView,
                    ProductUpdateView,
                )
app_name = 'product'
urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('<int:id>', ProductDetailView.as_view(),name='product-detail'),
    path('create/', ProductCreateView.as_view(),name='product-create'),
    path('<int:id>/update/', ProductUpdateView.as_view(),name='product-update'),
    path('<int:id>/delete/', ProductDeleteView.as_view(),name='product-delete'),
]

vx/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from product.views import (
                    ProductDetailView,
                    )
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home-page'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('product/', include('product.urls')),
    path('purchase/', include('purchase.urls')),
    path('sell/', include('sell.urls')),
    path('product/<int:id>/', ProductDetailView.as_view(),name='product-detail'),
    path('customer/', include('customer.urls')),

]

product/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    PRODUCER = (
        ('TE', 'Treofan'),
        ('JE', 'Jindal Europe'),
        ('JI', 'Jindal India'),
        ('JA', 'Jindal America')
    )
    producer = models.CharField(max_length=2,choices=PRODUCER, default='JE')
    name = models.CharField(max_length=20, unique=True)
    GROUP = (
        ('NPD', 'NPD'),
        ('SPP', 'Specialty Packaging'),
        ('SPL', 'Specialty Labeling'),
        ('IML', 'IML'),
        ('COM', 'Commodity')
    )
    group = models.CharField(max_length=3,choices=GROUP, default='NPD')
    FAMILY = (
        ('UW', 'Uncoated White'),
        ('CW', 'Coated White'),
        ('UT', 'Uncoated Transparent'),
        ('CT', 'Coated transparent'),
        ('MT', 'Metallised'),
        ('ST', 'SealTough'),
        ('AL', 'Alox'),
        ('HD', 'EthyLyte')
    )
    family = models.CharField(max_length=2,choices=FAMILY, default='UW')
    link = models.URLField(blank=True)

    class Meta:
        db_table = 'product'
        ordering = ('name','family',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product-detail', {'id':self.id})

product/forms.py
from django import forms
from .models import Product

class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []
        

product/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
                            CreateView,
                            DeleteView,
                            DetailView,
                            ListView,
                            UpdateView
)
from .models import Product
from .forms import ProductModelForm
from django.urls import reverse

class ProductListView(LoginRequiredMixin, ListView):
    model = Product

class ProductCreateView(LoginRequiredMixin, CreateView):
    template_name = 'product/product_create.html'
    form_class = ProductModelForm
    model = Product
    def get_success_url(self):
        return reverse('product:product-list')

class ProductDetailView(LoginRequiredMixin, DetailView):
    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Product, id=id_)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        ppp = kwargs.get('object', None)
        sell_product_list = ppp.product_sells.all()
        proj_product_list = ppp.product_projects.all()
        if sell_product_list or proj_product_list:
            context.update({'sell_product_list': sell_product_list, 'proj_product_list': proj_product_list})
        return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'product/product_create.html'
    form_class = ProductModelForm
    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Product, id=id_)
    def get_success_url(self):
        return reverse('product:product-list')

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'product/product_delete.html'
    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Product, id=id_)
    def get_success_url(self):
        return reverse('product:product-list')

product/templates/product/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form action='.' method="post">{% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Save">
</form>
<br>
<a class="btn btn-outline-info btn-sm" href="{% url 'product:product-list' %}">Back to Product List</a>

{% endblock %}

product/templates/product/product_delete.html
</form>
{% extends "product/product_detail.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong> {{ object.name }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

product/templates/product/product_detail.html
{% extends "base.html" %}
{% load table_operations %}
{% block head_title %}{{object.name}}{% endblock %}
{% block content %}

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Family</th>
      <th scope="col">Group</th>
      <th scope="col">Producer</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="table-success">{{ object.name }}</td>
      <td class="table-dark">{{ object.get_family_display }}</td>
      <td class="table-danger">{{ object.get_group_display }}</td>
      <td class="table-warning">{{ object.get_producer_display }}</td>
    </tr>
  </tbody>
</table>

<h4><a href="{{ object.link }}">Press here to see the product</a></h4>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group mr-2" role="group" aria-label="First group">
  <a class="btn btn-outline-warning btn-sm" href="{% url 'product:product-update' object.id %}">Update</a>
  <a class="btn btn-outline-danger btn-sm" href="{% url 'product:product-delete' object.id %}">Delete</a>
  <a class="btn btn-outline-info btn-sm" href="{% url 'product:product-list' %}">Product List</a>
</div>
</div>

<h4>{{object.name}} business:</h4>
<table id="mydatatable" class="display" style="width:100%">
  <thead>
    <tr>
      <th scope="col">Converter</th>
      <th scope="col">Enduser</th>
      <th scope="col">T pa</th>
      <th scope="col">Price</th>
      <th scope="col">EUR</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
{% for i in sell_product_list %}
    <tr>
      <td>{{ i.sell.converter.name }}</td>
      <td>{{ i.enduser.name }}</td>
      <td>{{ i.quantity }}</td>
      <td>{{ i.price }}</td>
      <td>{{ i.price|mult:i.quantity }}</td>
        {% if i.discontinued == True %}
        <td> discontinued!</td>
        {% else %}
        <td></td>
        {% endif %}
    </tr>
{% endfor %}
</tbody>
     <tfoot>
         <tr>
           <th scope="col">Converter</th>
           <th scope="col">Enduser</th>
           <th scope="col">T pa</th>
           <th scope="col">Price</th>
           <th scope="col">EUR</th>
           <th scope="col"></th>
          </tr>
     </tfoot>
 </table>

 <h4>{{object.name}} Projects:</h4>
 <table id="mydatatable" class="display" style="width:100%">
   <thead>
     <tr>
       <th scope="col">Fr-Part</th>
       <th scope="col">T pa</th>
       <th scope="col">Price</th>
       <th scope="col">Back-par</th>
       <th scope="col">Application</th>
       <th></th>
     </tr>
   </thead>
   <tbody>
 {% for i in proj_product_list %}
     <tr>
       <td>{{ i.front_partner.name }}</td>
       <td>{{ i.quantity }}</td>
       <td>{{ i.price }}</td>
       <td>{{ i.back_partner.name }}</td>
       <td>{{ i.application }}</td>
       {% if i.discontinued == True %}
         <td> discontinued!</td>
         {% else %}
         <td></td>
         {% endif %}
     </tr>
 {% endfor %}
 </tbody>
  </table>

{% endblock %}

product/templates/product/product_list.html
{% extends "base.html" %}
{% block content %}

<h4>Product</h4>
<a class="btn btn-outline-info btn-sm" href="{% url 'product:product-create' %}">Create new</a>

  <table id="mydatatable" class="display" style="width:100%">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Family</th>
        <th scope="col">Group</th>
        <th scope="col">Producer</th>
      </tr>
    </thead>
    <tbody>
{% for prod in object_list %}
      <tr>
        <td><a href="{% url 'product:product-detail' prod.id %}/">{{ prod.name }}</td>
        <td>{{ prod.family }}</td>
        <td>{{ prod.group }}</td>
        <td>{{ prod.producer }}</td>
      </tr>
{% endfor %}
</tbody>

   </table>

{% endblock %}