customer/urls.py
from django.urls import path
from .views import *


app_name = 'customer'

urlpatterns = [
    path('', CustomerList.as_view(), name='customer-list'),
    path('create/', CustomerCreate.as_view(), name='customer-create'),
    path('update/<int:id>/', CustomerUpdate.as_view(), name='customer-update'),
    path('<int:pk>/', CustomerDetail.as_view(),name='customer-detail'),
    path('delete/<int:pk>/', CustomerDelete.as_view(), name='customer-delete'),

	]

product/urls.py
from django.urls import path

from .views import (
                    ProductListView,
                    ProductDeleteView,
                    ProductDetailView,
                    ProductCreateView,
                    ProductUpdateView,
                )
app_name = 'product'
urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('<int:id>', ProductDetailView.as_view(),name='product-detail'),
    path('create/', ProductCreateView.as_view(),name='product-create'),
    path('<int:id>/update/', ProductUpdateView.as_view(),name='product-update'),
    path('<int:id>/delete/', ProductDeleteView.as_view(),name='product-delete'),
]

purchase/urls.py
from django.urls import path
from .views import *


app_name = 'purchase'

urlpatterns = [
    path('', PurchaseList.as_view(), name='purchase-list'),
    path('create/', PurchaseCreate.as_view(), name='purchase-create'),
    path('update/<int:pk>/', PurchaseUpdate.as_view(), name='purchase-update'),
    path('<int:pk>/', PurchaseDetail.as_view(),name='purchase-detail'),
    path('delete/<int:pk>/', PurchaseDelete.as_view(), name='purchase-delete'),

	]

sell/urls.py
from django.urls import path
from .views import *


app_name = 'sell'

urlpatterns = [
    path('', SellList.as_view(), name='sell-list'),
    path('active/', SellItemList.as_view(), name='active-list'),
    path('create/', SellCreate.as_view(), name='sell-create'),
    path('update/<int:pk>/', SellUpdate.as_view(), name='sell-update'),
    path('<int:pk>/', SellDetail.as_view(),name='sell-detail'),
    path('delete/<int:pk>/', SellDelete.as_view(), name='sell-delete'),

	]

vx/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from product.views import (
                    ProductDetailView,
                    )
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home-page'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('product/', include('product.urls')),
    path('purchase/', include('purchase.urls')),
    path('sell/', include('sell.urls')),
    path('product/<int:id>/', ProductDetailView.as_view(),name='product-detail'),
    path('customer/', include('customer.urls')),

]

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block head_title %}{% endblock %} </title>
{% include 'css.html' %}

<link rel="apple-touch-icon" href="/custom_icon.png"/>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class='container mb-3 mt-3'>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% block content %}
    {% endblock %}

</div>
{% include 'js.html' %}
  </body>
</html>

templates/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

templates/home.html
{% extends "base.html" %}

{% block head_title %}HOME{% endblock %}



{% block content %}

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRslH6D_8qeW4bI_dbIdPyEfaxtrNRGAGyKRz1z8DrcClygVa17" width="500" height="333">
<h1>{{ welcome }} {{ username }}</h1>

{% endblock %}

templates/js.html
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script><link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.20/af-2.3.4/b-1.6.1/b-colvis-1.6.1/b-html5-1.6.1/b-print-1.6.1/cr-1.5.2/fc-3.3.0/fh-3.1.6/kt-2.5.1/r-2.2.3/rg-1.1.1/rr-1.2.6/sp-1.0.1/sl-1.3.1/datatables.min.css"/>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.20/af-2.3.4/b-1.6.1/b-colvis-1.6.1/b-html5-1.6.1/b-print-1.6.1/cr-1.5.2/fc-3.3.0/fh-3.1.6/kt-2.5.1/r-2.2.3/rg-1.1.1/rr-1.2.6/sp-1.0.1/sl-1.3.1/datatables.min.js"></script>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.colVis.min.js"></script>

</script>

<script>
$(document).ready(function() {
  $('#mydatatable').DataTable( {

    // initComplete: function () {
    //             this.api().columns().every( function () {
    //                 var column = this;
    //                 var select = $('<select><option value=""></option></select>')
    //                     .appendTo( $(column.header()) )
    //                     .on( 'change', function () {
    //                         var val = $.fn.dataTable.util.escapeRegex(
    //                             $(this).val()
    //                         );
    //
    //                         column
    //                             .search( val ? '^'+val+'$' : '', true, false )
    //                             .draw();
    //                     } );
    //
    //                 column.data().unique().sort().each( function ( d, j ) {
    //                     select.append( '<option value="'+d+'">'+d+'</option>' )
    //                 } );
    //             } );
    //         },

    // order: [[0, 'desc']],
    pagingType: 'full_numbers',
    lengthMenu: [[-1,5,10,25,50], ["All",5,10,25,50]],


    dom: 'B<"clear">lfrtip',
    buttons: {
    name: 'primary',
    buttons: [
                { extend: 'copy', footer: true, exportOptions: {columns: ':visible'} },
                { extend: 'excel', footer: true, exportOptions: {columns: ':visible'}, filename:'Report' },
                { extend: 'csv', footer: true, exportOptions: {columns: ':visible'}, filename:'Report' },
                { extend: 'pdf', footer: true, exportOptions: {columns: ':visible'}, filename:'Report',exportOptions:{columns: [0, 1, 2, 3]} },
                { extend: 'print', footer: true, exportOptions: {columns: ':visible'},exportOptions:{columns: [0, 1, 2, 3]} },
                { extend: 'colvis', footer: true, exportOptions: {columns: ':visible'}},

            ]
    },



    "footerCallback": function ( row, data, start, end, display ) {
              var api = this.api(), data;

              // Remove the formatting to get integer data for summation
              var intVal = function ( i ) {
                  return typeof i === 'string' ?
                      i.replace(/[\$,]/g, '')*1 :
                      typeof i === 'number' ?
                          i : 0;
              };

              // Total over all pages
              total = api
                  .column( 2 )
                  .data()
                  .reduce( function (a, b) {
                      return (intVal(a) + intVal(b)).toFixed(0);
                  }, 0 );

              // Total over this page
              pageTotal = api
                  .column( 2, { page: 'current'} )
                  .data()
                  .reduce( function (a, b) {
                      return (intVal(a) + intVal(b)).toFixed(0);
                  }, 0 );


              // Update footer
              $( api.column( 2 ).footer() ).html(
                  ''+pageTotal +' ( '+ total +' all pages)'
              );

              // Total over all pages
              total = api
                  .column( 4 )
                  .data()
                  .reduce( function (a, b) {
                      return (intVal(a) + intVal(b)).toFixed(0);
                  }, 0 );

              // Total over this page
              pageTotal = api
                  .column( 4, { page: 'current'} )
                  .data()
                  .reduce( function (a, b) {
                      return (intVal(a) + intVal(b)).toFixed(0);
                  }, 0 );


              // Update footer
              $( api.column( 4 ).footer() ).html(
                  ''+pageTotal +' ( '+ total +' all pages)'
              );


        },

  } );
} );

</script>

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
<form method="post">
  {% csrf_token %}
  <fieldset class='form-group'>
    <legend class="border-bottom mb-4">Log In</legend>
    {{ form|crispy }}
  </fieldset>
  <div class="form-group">
    <button class='btn btn-outline-info' type='submit'>Login</button>
  </div>
</form>

  </div>

{% endblock %}

templates/logout.html
{% extends "base.html" %}
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
 <a href="{% url 'login' %}">Log In Again</a></small>
</div>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Volo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
  {% if user.is_staff %}
  <li class="nav-item active">
      <a class="nav-link" href="{% url 'logout' %}">Log out<span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item active">
      <a class="nav-link" href="{% url 'home-page' %}">Home<span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item active">
      <a class="nav-link" href="{% url 'product:product-list' %}">Films<span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Projects
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'purchase:purchase-list' %}">Detailed</a>
          <!-- <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
  </li>

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'customer:customer-list' %}">Customers<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sell:active-list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Business
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sell:sell-list' %}">History</a>
              <a class="dropdown-item" href="{% url 'sell:active-list' %}">Active</a>
              <!-- <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a> -->
            </div>
      </li>

    </ul>
  {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Log in<span class="sr-only">(current)</span></a>
      </li>
  {% endif %}
  </div>
</nav>